config/routes.rb
Rails.application.routes.draw do
  
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'welcome#home'
  
  resources :welcome, only: [:home, :create]
  
  get "/searches/new" => redirect("/#eventfinder")
 
  devise_for :users, controllers: {registrations: 'registrations'}
  
  resources :events
  
  resources :searches

  
  
  

end

app/models/event.rb
class Event < ActiveRecord::Base
   
  validates :user_id, presence: true  
  
  
  belongs_to :user

 has_attached_file :image
 
 validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/pdf"],
 
 :s3_region => ENV['AWS_REGION'],
 
  :storage => :s3
 #mount_uploader :image, ImageUploader
   
end

app/models/search.rb
class Search < ActiveRecord::Base
  
  
  def search_events
    
    events = Event.all
    
    events = events.where(["name LIKE ?", "%#{performer}%"]) if performer.present?
    events = events.where(["category LIKE ?", genre]) if genre.present?
    events = events.where(["location LIKE ?", place]) if place.present?
    events = events.where(["eventtime >= ?", searchtime]) if searchtime.present?
    events = events.where(["date = ?", date]) if date.present?
    events = events.where(["description LIKE ?", about]) if about.present?
    
    
    return events
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  
  
  has_many :events, dependent: :destroy  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/models/welcome.rb
class Welcome < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact You",
      :to => "kilkennylive@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def stored_location_for(resource)
   nil
  end

def after_sign_in_path_for(resource)
  events_path
end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
    
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "Your post has been created!"
      redirect_to events_path
    else
      flash[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :category, :location, :description, :image, :venue_name, :date, :eventtime)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
private

def sign_up_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

def account_update_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
end
end


app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
def create
  @search = Search.create(search_params)
  redirect_to @search 
end

def show
  @search = Search.find(params[:id])
end

private 

def search_params
  params.require(:search).permit(:performer, :genre, :place, :about, :date, :searchtime)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def home
    @search = Search.new
    @performers = Event.uniq.pluck(:name)
    @genres = Event.uniq.pluck(:category)
    @places = Event.uniq.pluck(:location)
    @searchtimes = Event.uniq.pluck(:eventtime)
    @contact = Welcome.new(params[:welcome])
  end

  def create
    @contact = Welcome.new(params[:welcome])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Welcome.new
        format.html { render 'home'}
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'home' }
        format.js   { flash.now[:error] = @message = "Message did not send." }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>

  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
    <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
  	<% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
	<%= f.label :start_time %><br/>
	<%= f.select :eventtime, options_for_select([['10:30am', '10:30am'], ['11:00am', '11:00am'], ['11:30am', '11:30am'], ['12:00pm', '12:00pm'], ['12:30am', '12:30am'], ['13:00pm', '13:00pm'], 
	['13:30pm', '13:30pm'], ['14:00pm', '14:00pm'], ['14:30pm', '14:30pm'], ['15:00pm', '15:00pm'], ['15:30pm', '15:30pm'],['16:00pm', '16:00pm'], ['16:30pm', '16:30pm'], ['17:00pm', '17:00pm'], 
	['17:30pm', '17:30pm'],['18:00pm', '18:00pm'], ['18:30pm', '18:30pm'], ['19:00pm', '19:00pm'], ['19:30pm', '19:30pm'], ['20:00pm', '20:00pm'], ['20:30pm', '20:30pm'],['21:00pm', '21:00pm'], 
	['21:30pm', '21:30pm'],['22:00pm', '22:00pm'], ['22:30pm', '22:30pm'],['23:00pm', '23:00pm'], ['23:30pm', '23:30pm'], ['00:00am', '00:00am'], ['00:30pm', '00:30pm'],
	['1:00am', '1:00am']], @event.eventtime), {:prompt => ''}, {:style => 'width: 25%;'}%>
  </div>
  
  <div class="field">
  	<%= f.label :category %><br>
    <%= f.select :category, options_for_select([['Irish', 'Irish'], ['Rock', 'Rock'], ['Comedy', 'Comedy'], ['Jazz', 'Jazz'], ['DJ', 'DJ'], 
    ['Theatre', 'Theatre']], @event.category), {:prompt => ''}, {:style => 'width: 25%;'}%>
  </div>
  
  <div class="field">
    <%= f.label :location %><br>
    <%= f.select :location, options_for_select([['Kilkenny', 'Kilkenny'], ['Dublin', 'Dublin'], ['Waterford', 'Waterford'], 
    ['Cork', 'Cork']], @event.location), {:prompt => ''}, {:style => 'width: 25%;'}%>
  </div>
  
  <div class="field">
	<%= f.label :date %><br/>
	<%= f.date_field :date, :style => 'width: 25%;' %>
  </div>
 
  <div class="field">
    <%= f.label :venue_name %><br>
    <%= f.text_field :venue_name, :style => 'width: 25%;' %>
  </div>
  
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :name, :style => 'width: 25%;' %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :style => 'width: 25%;', :size => '20x3' %>
  </div>
  
  <div align="center">
  	<%= f.label :image %><br> 
    <%= f.file_field :image, :style => 'width: 25%;' %>
  </div><br>
  
  <div class="actions"><%= f.submit "Create Event", class: "btn btn-xl"%></div>
  </div>
  
  <% end %>

app/views/events/edit.html.erb
<%= render 'layouts/navbar' %>


	<div class="container">
		<div class="eventmaincontainer">
            <div class="row">
                <div class="col-lg-12 text-center">

					<h1>Editing Event</h1>
					
<div class="row">
      	<div class="col-md-4 text-center col-md-offset-4">
             	<div class="event-container">					
<%= form_for @event, html: { multipart: true } do |f| %>

  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
    <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
  	<% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
	<%= f.label :start_time %><br/>
	<%= f.select :eventtime, options_for_select([['10:30am', '10:30am'], ['11:00am', '11:00am'], ['11:30am', '11:30am'], ['12:00pm', '12:00pm'], ['12:30am', '12:30am'], ['13:00pm', '13:00pm'], 
	['13:30pm', '13:30pm'], ['14:00pm', '14:00pm'], ['14:30pm', '14:30pm'], ['15:00pm', '15:00pm'], ['15:30pm', '15:30pm'],['16:00pm', '16:00pm'], ['16:30pm', '16:30pm'], ['17:00pm', '17:00pm'], 
	['17:30pm', '17:30pm'],['18:00pm', '18:00pm'], ['18:30pm', '18:30pm'], ['19:00pm', '19:00pm'], ['19:30pm', '19:30pm'], ['20:00pm', '20:00pm'], ['20:30pm', '20:30pm'],['21:00pm', '21:00pm'], 
	['21:30pm', '21:30pm'],['22:00pm', '22:00pm'], ['22:30pm', '22:30pm'],['23:00pm', '23:00pm'], ['23:30pm', '23:30pm'], ['00:00am', '00:00am'], ['00:30pm', '00:30pm'],
	['1:00am', '1:00am']], @event.eventtime), {:prompt => ''}, {:style => 'width: 70%;'}%>
  </div>
  
  <div class="field">
  	<%= f.label :category %><br>
    <%= f.select :category, options_for_select([['Irish', 'Irish'], ['Rock', 'Rock'], ['Comedy', 'Comedy'], ['Jazz', 'Jazz'], ['DJ', 'DJ'], 
    ['Theatre', 'Theatre']], @event.category), {:prompt => ''}, {:style => 'width: 70%;'}%>
  </div>
  
  <div class="field">
    <%= f.label :location %><br>
    <%= f.select :location, options_for_select([['Kilkenny', 'Kilkenny'], ['Dublin', 'Dublin'], ['Waterford', 'Waterford'], 
    ['Cork', 'Cork']], @event.location), {:prompt => ''}, {:style => 'width: 70%;'}%>
  </div>
  
  <div class="field">
	<%= f.label :date %><br/>
	<%= f.date_field :date, :style => 'width: 70%;' %>
  </div>
 
  <div class="field">
    <%= f.label :venue_name %><br>
    <%= f.text_field :venue_name, :style => 'width: 70%;' %>
  </div>
  
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :name, :style => 'width: 70%;' %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :style => 'width: 70%;', :size => '20x3' %>
  </div>
  
  <div align="center">
  	<%= f.label :image %><br> 
    <%= f.file_field :image, :style => 'width: 70%;' %>
  </div><br>
  
  <div class="actions"><%= f.submit "Update Event", class: "btn btn-xl"%></div>
  </div>
  
  <% end %>
					
					<%= link_to 'Show', @event %> |
					<%= link_to 'Back', events_path %>
			</div>
		</div>
	</div>
</div>
</div>
</div>
</div>

app/views/events/index.html.erb
<!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top affix navbar-shrink">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Live Event Guide</a>
               </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <% if user_signed_in? %>
                   
                    <li>
                       <%= link_to 'Home', root_path %>
                    </li>
                    <li>
                        <%= link_to "Logout", destroy_user_session_path, :method => 'delete'%>
                    </li>
                    
                    
                    <%else%>
                    
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                   
                    <li>
                        <a class="page-scroll" href="#eventfinder">Event Finder</a>
                    </li>
                   
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                    
                    <li>
                        <a class="page-scroll" href="#login">Login</a>
                    </li>
                    <%end%>
                    
                </ul>
                  
                </ul>
                
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
<br>
	<br>
		<br>
			<div class="container">
            	<br>
            		<p id="notice"><%= notice %></p>
						<h1 style="text-align: center;">Listing Events<br>
							<br><%= link_to "New Event", new_event_path, :class => "btn btn-xl"%></h1>
								<br>
									<div class="table-responsive">
										<table class="table table-striped table-condensed">
															
										  <thead>
										    <tr>
										      <th>Image<br></th> 
										      <th>Name</th>
										      <th>Venue<br></th> 
										      <th>Category</th>
										      <th>Location</th>
										      <th>Time</th>
										      <th>Date</th>
										      <th>Description</th>
										      <th colspan="3"></th>
										    </tr>
										  </thead>
					
										  <tbody>
										    <% @events.each do |event| %>
										      <tr>
										      	<td><%= image_tag event.image.url, size:"100x100" %></td>
										        <td><%= event.name %></td>
										        <td><%= event.venue_name %></td>
										        <td><%= event.category %></td>
										        <td><%= event.location %></td>
										        <td><%= event.eventtime %></td>
										        <td><%= event.date %></td>
										        <td><%= event.description %></td>
										        <td><%= link_to 'Show', event %></td>
										        <td><%= link_to 'Edit', edit_event_path(event) %></td>
										        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
										      </tr>
										    <% end %>
										  </tbody>
										</table>
									</div>
								</div>	
							<br>
								

app/views/events/new.html.erb
<%= render 'layouts/navbar' %>

<body class="events-bg">
	<div class="container">
		<div class="eventmaincontainer">
            <div class="row">
                <div class="col-lg-12 text-center">
                	
						<h1>New Event</h1><br>
						
						<%= render 'events/form' %><br>
						
						<%= link_to 'Back', events_path %>
						</div>
				</div>
			</div>
		</div>
</body>

app/views/events/show.html.erb
<%= render 'layouts/navbar' %>


	<div class="container">
			<div class="eventmaincontainer">
	            <div class="row">
	                <div class="col-sm-12 text-center">

					<h1>Showing Event</h1>

						<p id="notice"><%= notice %></p>
						
						<p>
						  <strong>Image:</strong><br>
						  <%= image_tag @event.image.url, size:"200x200" %>
						</p>
						
						<p>
						  <strong>Name:</strong>
						  <%= @event.name %>
						</p>
						
						<p>
						  <strong>Venue:</strong>
						  <%= @event.venue_name %>
						</p>
						
						<p>
						  <strong>Category:</strong>
						  <%= @event.category %>
						</p>
						
						<p>
						  <strong>Location:</strong>
						  <%= @event.location %>
						</p>
						
						<p>
						  <strong>Time:</strong>
						  <%= @event.eventtime %>
						</p>
						
						<p>
						  <strong>Date:</strong>
						  <%= @event.date %>
						</p>
						
						<p>
						  <strong>Description:</strong><br>
						  <%= @event.description %>
						</p>
						<p>	
						<%= link_to 'Edit', edit_event_path(@event) %> |
						<%= link_to 'Back', events_path %>
							
						</div>
					</div>
				</div>
			</div>
		<br>
			
			
						
						

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top affix navbar-shrink">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Kilkenny Live</a>
               </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <% if user_signed_in? %>
                    <li>
                       	<%= link_to 'Back', events_path %>
                    </li>
                    <li>
                        <%= link_to 'Home', root_path %>
                    </li>
                    <li>
                        <%= link_to "Logout", destroy_user_session_path, :method => 'delete'%>
                    </li>
                    
                    
                    <%else%>
                    
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                   <!-- <li>
                        <a class="page-scroll" href="#services">Services</a>
                   </li> -->
                    <li>
                        <a class="page-scroll" href="#eventfinder">Event Finder</a>
                    </li>
                    <!-- <li>
                        <a class="page-scroll" href="#portfolio">Venues</a>
                    </li> -->
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                    
                    <li>
                        <a class="page-scroll" href="#login">Login</a>
                    </li>
                    <%end%>
                    
                </ul>
                    
                    
                   <!-- <li>
                        <a class="page-scroll" href="#services">Services</a>
                   </li> 
                    <li>
                        <a class="page-scroll" href="#about">Event Finder</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="#portfolio">Venues</a>
                    </li> 
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#login">Login</a>
                    </li>-->
                    
                </ul>
                
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

app/views/layouts/_resultsnav.html.erb
<!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top affix navbar-shrink">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Kilkenny Live</a>
               </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    
                    <li>
                       <%= link_to 'Home', root_path %>
                    </li>     
                </ul>
                    
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>	
    
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>-->
  
      

  

  <%= csrf_meta_tags %>
  
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	
  <title>Kilkenny Live</title>
    
     <!-- Plugin JavaScript -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
		
    <%= yield %>

</body>

<footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Alan Kelly 2016</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        
</footer>

</html>

app/views/searches/new.html.erb
<h1> Advanced Search</h1>

<div class="eventsearch">
<%= form_for @search , html: {class: "pure-form"} do |s|%>
    
    <div class="field">
		<%= s.label :time_from %> <br>
		<%= s.select :searchtime, options_for_select(@searchtimes), :include_blank => true %>
	</div> <br>
    
    <div class="field">
    	<%= s.label :about %><br/>
    	<%= s.text_field :about  %>
    </div>
    
    <div class="field">
    	<%= s.label :performer %><br/>
    	<%= s.select :performer, options_for_select(@performers), :include_blank => true %>
    </div>
    	
    <div class="field">
    	<%= s.label :genre %><br/>
    	<%= s.select :genre, options_for_select(@genres), :include_blank => true, size: "240x6"  %>
    	</div>
    	
    <div class="field">
    	<%= s.label :place %><br/>
    	<%= s.select :place, options_for_select(@places), :include_blank => true %>
    </div>
    	
    <div class="actions"><%= s.submit "Search", class: "pure-button pure-button-primary"%></div>
    	
    <%end%>
    	
    <p><%= link_to 'Back', events_path %></p>
    	
    	</div>


app/views/welcome/_contact_form.erb
<%= form_for @contact, url: welcome_index_path, remote: true do |f| %>
                  
                </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <%= f.text_field  :name, required: true, class: "form-control", placeholder: "Full Name..."%></br>
                        </div>
                        
                        <div class="form-group">
                            <%= f.text_field :email, required: true, class: "form-control", placeholder: "Your Email Address..."%></br>
                        </div>
                        
                        <div class="col-lg-12 text-center">
                          <%= f.submit 'Send Message', class: 'btn btn-primary', data: { disable_with: "Submitting..."} %>
                    </div>
                    </div>
                    
                    <div class="col-md-6">
                        <div class="form-group">
                              <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "form-control",
                                                placeholder: "Place Your Message Here..."%></br>
                        </div>
                    </div>
                    
                      <div class= "hidden">
                        <%= f.label :nickname %>
                        <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
                      </div>
                      
              </div>
      </div>
            

 <% end %>

<div class="col-md-3" id="flash-message">
                <%= render 'flash' %>
            </div>

app/views/welcome/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/welcome/create.js.erb
// Test for ajax success
console.log("This is the create.js.erb file");
// Render flash message
$("#foo")[0].reset();
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);